"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

const categories=[
 {name:"Images",icon:"◫",description:"Resize, compress, convert and understand your images.",tools:["Print Size Calculator","DPI Calculator","Pixels to Inches","Image Resolution Checker","Image Format Converter","Image Resizer","Image Compressor","Image Cropper"]},
 {name:"PDF & Documents",icon:"▤",description:"Turn text into documents and keep simple file workflows moving.",tools:["Text to PDF"]},
 {name:"Developer",icon:"</>",description:"Format, encode, validate and transform technical data.",tools:["JSON Formatter","JSON Minifier","Base64 Encoder","Base64 File Encoder","UUID Generator","Bulk UUID Generator","URL Encoder / Decoder","URL Parser","Regex Tester","HTML Entity Encoder","HTML Minifier","Markdown to HTML","Unix Timestamp Converter","SHA-256 Hash Generator","JWT Decoder"]},
 {name:"Text & Productivity",icon:"Aa",description:"Write, count, compare and focus without the clutter.",tools:["Typing Test","Word Counter","Character Counter","Pomodoro Timer","Countdown Timer","Text Case Converter","Remove Duplicate Lines","Text Sorter","Text Diff"]},
 {name:"Everyday",icon:"✦",description:"Small utilities for decisions, colors, QR codes and more.",tools:["Password Generator","Random Number Generator","Coin Flip","Online Ruler","QR Code Generator","Stopwatch","Color Converter","URL Slug Generator","Percentage Calculator","Age Calculator","JSON to CSV","CSV to JSON"]}
] as const;
const slug=(name:string)=>({"Print Size Calculator":"print-size-calculator","DPI Calculator":"dpi-calculator","Pixels to Inches":"pixels-to-inches","Image Resolution Checker":"image-resolution-checker","Image Format Converter":"image-converter","Image Resizer":"image-resizer","Image Compressor":"image-compressor","Image Cropper":"image-cropper","Text to PDF":"text-to-pdf","JSON Formatter":"json-formatter","JSON Minifier":"json-minifier","Base64 Encoder":"base64-encoder","Base64 File Encoder":"base64-file","UUID Generator":"uuid-generator","Bulk UUID Generator":"uuid-bulk-generator","URL Encoder / Decoder":"url-encoder-decoder","URL Parser":"url-parser","Regex Tester":"regex-tester","HTML Entity Encoder":"html-entity-encoder","HTML Minifier":"html-minifier","Markdown to HTML":"markdown-to-html","Unix Timestamp Converter":"timestamp-converter","SHA-256 Hash Generator":"hash-generator","JWT Decoder":"jwt-decoder","Typing Test":"typing-test","Word Counter":"word-counter","Character Counter":"character-counter","Pomodoro Timer":"pomodoro-timer","Countdown Timer":"countdown-timer","Text Case Converter":"text-case-converter","Remove Duplicate Lines":"remove-duplicate-lines","Text Sorter":"text-sorter","Text Diff":"text-diff","Password Generator":"password-generator","Random Number Generator":"random-number-generator","Coin Flip":"coin-flip","Online Ruler":"online-ruler","QR Code Generator":"qr-code-generator","Stopwatch":"stopwatch","Color Converter":"color-converter","URL Slug Generator":"slug-generator","Percentage Calculator":"percentage-calculator","Age Calculator":"age-calculator","JSON to CSV":"json-to-csv","CSV to JSON":"csv-to-json"}[name]||"");
const popular=["Image Compressor","Image Resizer","Image Format Converter","Typing Test","JSON Formatter","QR Code Generator","Online Ruler","Password Generator"];
const all=categories.flatMap(c=>c.tools.map(name=>({name,category:c.name,href:`/${slug(name)}/`})));

export default function Home(){
 const [query,setQuery]=useState("");
 const results=useMemo(()=>all.filter(t=>(t.name+" "+t.category).toLowerCase().includes(query.toLowerCase())).slice(0,8),[query]);
 return <main>
  <header className="siteHeader"><Link className="brand" href="/"><strong>Fame</strong>Orbit</Link><nav><a href="#popular">Popular</a><a href="#categories">Categories</a><a href="#all-tools">All tools</a></nav><span className="headerTag">FREE · PRIVATE · FAST</span></header>
  <section className="homeHero"><div className="eyebrow">THE EVERYDAY WEB TOOLKIT</div><h1>What do you need<br/><em>to get done?</em></h1><p>Fast, focused tools for images, text, developers and everyday tasks. No account. No upload by default. Just get it done.</p>
   <div className="toolSearch"><span>⌕</span><input aria-label="Search tools" placeholder="Search a tool — try “compress”, “json”, “typing”..." value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></div>
   {query&&<div className="searchResults">{results.length?results.map(t=><Link href={t.href} key={t.name}><span>{t.name}</span><small>{t.category}</small><b>↗</b></Link>):<div className="noResults">No matching tool yet.</div>}</div>}
   <div className="heroMeta"><span>✓ Runs in your browser</span><span>✓ No signup</span><span>✓ Built for speed</span></div>
  </section>
  <section className="trustStrip"><span>PRIVATE BY DEFAULT</span><i/><span>NO SIGN-UP</span><i/><span>FAST IN YOUR BROWSER</span><i/><span>FREE TO USE</span></section>
  <section className="homeSection" id="popular"><div className="sectionHead"><div><div className="eyebrow">START HERE</div><h2>Popular tools</h2></div><p>Quick answers to the things people search for most.</p></div><div className="popularGrid">{popular.map((name,i)=><Link href={`/${slug(name)}/`} className="popularCard" key={name}><span className="popularIcon">{["◫","↔","⇄","⌨","{ }","▦","▥","⚿"][i]}</span><div><small>0{i+1}</small><h3>{name}</h3><p>{categories.find(c=>c.tools.includes(name as never))?.description}</p></div><b>↗</b></Link>)}</div></section>
  <section className="homeSection" id="categories"><div className="sectionHead"><div><div className="eyebrow">WORKFLOWS</div><h2>Tools that work together.</h2></div><p>Pick a task, then move naturally to the next step instead of starting over.</p></div><div className="categoryCards">{categories.map(c=><article key={c.name}><div className="categoryIcon">{c.icon}</div><div><h3>{c.name}</h3><p>{c.description}</p></div><div className="categoryLinks">{c.tools.slice(0,4).map(t=><Link href={`/${slug(t)}/`} key={t}>{t}<span>↗</span></Link>)}</div><Link className="categoryMore" href={`#all-tools`}>View all {c.tools.length} tools →</Link></article>)}</div></section>
  <section className="privacyBanner"><div><span className="privacyIcon">⌁</span><div><div className="eyebrow">PRIVACY-FIRST DESIGN</div><h2>Your files stay yours.</h2><p>Whenever a tool can run locally, FameOrbit processes it in your browser. We don't need your files to make the tool useful.</p></div></div><span className="privacyPill">🔒 PRIVATE BY DEFAULT</span></section>
  <section className="homeSection allTools" id="all-tools"><div className="sectionHead"><div><div className="eyebrow">THE FULL TOOLKIT</div><h2>Everything, organized.</h2></div><p>{all.length} focused tools and growing.</p></div><div className="allToolGrid">{all.map((t,i)=><Link href={t.href} key={t.name}><span>{String(i+1).padStart(2,"0")}</span><div><strong>{t.name}</strong><small>{t.category}</small></div><b>↗</b></Link>)}</div></section>
  <footer><div><Link className="brand" href="/"><strong>Fame</strong>Orbit</Link><p>Small tools. Done properly.</p></div><div><Link href="/about/">About</Link><Link href="/privacy/">Privacy</Link><Link href="/terms/">Terms</Link></div></footer>
 </main>;
}
