"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import AdSlot from "../components/AdSlot";

export default function WordCounter() {
  const [text, setText] = useState("");
  const stats = useMemo(() => { const words = text.trim() ? text.trim().split(/\s+/).length : 0; const sentences = text.trim() ? (text.match(/[.!?]+(?=\s|$)/g) || []).length : 0; const reading = words ? Math.max(1, Math.ceil(words / 200)) : 0; return { words, sentences, reading }; }, [text]);
  return <main><header className="siteHeader"><Link className="brand" href="/"><strong>Fame</strong>Orbit</Link><span className="headerTag">PRODUCTIVITY · WORD COUNTER</span></header><section className="hero"><div className="eyebrow">WRITE WITH CONFIDENCE</div><h1>Count your words,<br/><em>instantly.</em></h1><p className="lead">A fast word counter with reading-time and sentence estimates. Everything runs locally in your browser.</p><div className="panel custom"><h2>Your text</h2><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Start typing or paste your text here..." rows={12} style={{width:"100%",resize:"vertical",font:"inherit",padding:"18px",borderRadius:"14px",border:"1px solid rgba(20,20,18,.14)",background:"#fffdf8",boxSizing:"border-box"}}/><div className="summary"><div><span className="muted">WORDS</span><strong className="big">{stats.words}</strong></div><div><span className="muted">SENTENCES</span><strong className="big">{stats.sentences}</strong></div><div><span className="muted">READING TIME</span><strong className="big">{stats.reading ? `${stats.reading} min` : "—"}</strong></div></div></div><p className="muted">Nothing is uploaded. Your text stays in this browser.</p></section><AdSlot placement="after-calculator"/><section className="contentSection"><div className="contentInner"><div className="eyebrow">WORD COUNTING MADE SIMPLE</div><h2>Useful stats without the clutter.</h2><p>Use FameOrbit's word counter for essays, articles, applications, posts and everyday writing. Words are separated by whitespace, while sentence counts use common punctuation.</p><div className="guideGrid"><article><h3>Word count</h3><p>Words are counted from the text you enter, including pasted content.</p></article><article><h3>Reading time</h3><p>The estimate uses roughly 200 words per minute, a useful general benchmark.</p></article><article><h3>Private by design</h3><p>Your writing is processed directly in your browser rather than sent to a server.</p></article></div></div></section><footer><span>FameOrbit · Word Counter</span><Link href="/">Explore all FameOrbit tools</Link></footer></main>;
}
