"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import AdSlot from "../components/AdSlot";

export default function OnlineRuler(){
 const [pixelsPerCm,setPixelsPerCm]=useState(37.8);const [calibrated,setCalibrated]=useState(false);const [cm,setCm]=useState(10);const [unit,setUnit]=useState<"cm"|"in">("cm");
 useEffect(()=>{const saved=Number(localStorage.getItem("fameorbit-ruler-ppcm"));if(saved>10){setPixelsPerCm(saved);setCalibrated(true)}},[]);
 const px=cm*pixelsPerCm;const display=unit==="cm"?cm:cm/2.54;const marks=useMemo(()=>Array.from({length:Math.max(2,Math.floor(cm)+1)},(_,i)=>i),[cm]);
 const calibrate=()=>{const value=prompt("Measure a known 10 cm object against your screen and enter its pixel width:",String(Math.round(pixelsPerCm*10)));const n=Number(value);if(n>0){const p=n/10;setPixelsPerCm(p);setCalibrated(true);localStorage.setItem("fameorbit-ruler-ppcm",String(p))}};
 return <main>
  <header className="siteHeader"><Link className="brand" href="/"><strong>Fame</strong>Orbit</Link><nav><Link href="/">All tools</Link><Link href="/qr-code-generator/">QR Generator</Link><Link href="/percentage-calculator/">Calculators</Link></nav><span className="headerTag">EVERYDAY · MEASUREMENT</span></header>
  <section className="hero"><div className="eyebrow">MEASURE ON SCREEN</div><h1>A ruler that<br/><em>lives in your browser.</em></h1><p className="lead">Measure in real-world units, calibrate once, and keep the interface out of your way.</p>
   <div className="panel custom"><div className="typingTop"><div><span className="small">SCREEN RULER</span><h2>{calibrated?"Calibrated display":"Quick estimate"}</h2></div><span className={`status ${calibrated?"excellent":""}`}>{calibrated?"CALIBRATED":"ESTIMATE"}</span></div><div className="rulerToolbar"><div className="unitSwitch"><button className={unit==="cm"?"active":""} onClick={()=>setUnit("cm")}>cm</button><button className={unit==="in"?"active":""} onClick={()=>setUnit("in")}>in</button></div><button className="secondaryAction" onClick={calibrate}>Calibrate</button></div><div className="rulerWrap"><div className="rulerScale" style={{width:`${Math.min(px,900)}px`}}>{marks.map(i=><span key={i} style={{left:`${i/Math.max(marks.length-1,1)*100}%`}}>{i}</span>)}</div></div><label className="toolLabel">LENGTH ({unit.toUpperCase()})<input className="toolInput" type="number" min="1" max="24" step="0.1" value={display.toFixed(1)} onChange={e=>{const n=Number(e.target.value)||1;setCm(unit==="cm"?n:n*2.54)}}/></label><div className="customResult"><strong>{display.toFixed(1)} {unit}</strong><span className="status">{Math.round(px)} px</span><p>{calibrated?"Based on your saved screen calibration.":"Calibrate for a more accurate physical measurement."}</p></div></div>
  </section><AdSlot placement="after-calculator"/><section className="contentSection"><div className="contentInner"><div className="eyebrow">CALIBRATION</div><h2>Make the screen match reality.</h2><p>Browsers cannot automatically know the physical size of your display. FameOrbit lets you compare the ruler with a known object, save the result locally, and reuse it on future visits.</p><div className="guideGrid"><article><h3>1. Use 100% zoom</h3><p>Keep browser zoom at 100% before calibrating so the scale is not altered.</p></article><article><h3>2. Match a known size</h3><p>Use a physical ruler or a known-size object and enter the measured pixel length.</p></article><article><h3>3. Measure</h3><p>Place your object against the ruler and switch between centimetres and inches as needed.</p></article></div></div></section><footer><span>FameOrbit · Online Ruler</span><Link href="/">Explore all tools</Link></footer>
 </main>
}
