"use client";
import Link from "next/link";
import { useState } from "react";
import AdSlot from "../components/AdSlot";

export default function JSONFormatter() {
  const [input, setInput] = useState("");
  const [output, setOutput] = useState("");
  const [error, setError] = useState("");
  const format = () => { try { const value=JSON.parse(input); setOutput(JSON.stringify(value,null,2)); setError(""); } catch(e) { setOutput(""); setError(e instanceof Error ? e.message : "Invalid JSON"); } };
  const minify = () => { try { const value=JSON.parse(input); setOutput(JSON.stringify(value)); setError(""); } catch(e) { setOutput(""); setError(e instanceof Error ? e.message : "Invalid JSON"); } };
  const copy = () => navigator.clipboard?.writeText(output);
  return <main><header className="siteHeader"><Link className="brand" href="/"><strong>Fame</strong>Orbit</Link><span className="headerTag">DEVELOPER TOOL · JSON FORMATTER</span></header><section className="hero"><div className="eyebrow">FORMAT · VALIDATE · MINIFY</div><h1>Clean JSON,<br/><em>without the headache.</em></h1><p className="lead">Paste JSON, format it for readability, validate its syntax or minify it for compact output. Processing happens locally.</p><div className="panel custom"><h2>JSON input</h2><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder={'{"name":"FameOrbit","free":true}'} rows={12} spellCheck={false} style={{width:"100%",resize:"vertical",font:"ui-monospace, SFMono-Regular, Menlo, monospace",padding:"18px",borderRadius:"14px",border:"1px solid rgba(20,20,18,.14)",background:"#fffdf8",boxSizing:"border-box"}}/><div className="heroActions"><button className="primaryAction" type="button" onClick={format}>Format JSON ↗</button><button className="secondaryAction" type="button" onClick={minify}>Minify</button></div>{error && <p className="status low-resolution" style={{marginTop:"16px",display:"inline-block"}}>{error}</p>}{output && <><h2 style={{marginTop:"28px"}}>Output</h2><pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere",padding:"18px",borderRadius:"14px",background:"#171715",color:"#f7f4ec",overflowX:"auto"}}>{output}</pre><button className="secondaryAction" type="button" onClick={copy}>Copy output</button></>}</div><p className="muted">Your JSON never leaves this browser.</p></section><AdSlot placement="after-calculator"/><section className="contentSection"><div className="contentInner"><div className="eyebrow">JSON TOOLKIT</div><h2>Format and validate in seconds.</h2><p>JSON is commonly used for APIs, configuration and data exchange. Formatting makes nested data easier to inspect, while parsing catches syntax errors before you send it elsewhere.</p><div className="guideGrid"><article><h3>Format</h3><p>Pretty-print valid JSON with two-space indentation.</p></article><article><h3>Minify</h3><p>Remove unnecessary whitespace for compact JSON output.</p></article><article><h3>Local processing</h3><p>Your data stays in your browser while you work.</p></article></div></div></section><footer><span>FameOrbit · JSON Formatter</span><Link href="/">Explore all FameOrbit tools</Link></footer></main>;
}
