"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import AdSlot from "../components/AdSlot";

export default function CharacterCounter() {
  const [text, setText] = useState("");
  const stats = useMemo(() => { const words = text.trim() ? text.trim().split(/\s+/).length : 0; const noSpaces = text.replace(/\s/g, "").length; const lines = text ? text.split(/\r?\n/).length : 0; return { chars: text.length, noSpaces, words, lines }; }, [text]);
  return <main><header className="siteHeader"><Link className="brand" href="/"><strong>Fame</strong>Orbit</Link><span className="headerTag">PRODUCTIVITY · CHARACTER COUNTER</span></header><section className="hero"><div className="eyebrow">COUNT EVERY CHARACTER</div><h1>Characters, words,<br/><em>all in one view.</em></h1><p className="lead">Count characters with and without spaces, plus words and lines. Perfect for social posts, forms and writing limits.</p><div className="panel custom"><h2>Your text</h2><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Type or paste text here..." rows={12} style={{width:"100%",resize:"vertical",font:"inherit",padding:"18px",borderRadius:"14px",border:"1px solid rgba(20,20,18,.14)",background:"#fffdf8",boxSizing:"border-box"}}/><div className="summary"><div><span className="muted">CHARACTERS</span><strong className="big">{stats.chars}</strong></div><div><span className="muted">WITHOUT SPACES</span><strong className="big">{stats.noSpaces}</strong></div><div><span className="muted">WORDS</span><strong className="big">{stats.words}</strong></div></div><div className="row"><span>Lines</span><strong>{stats.lines}</strong><span className="status">LIVE</span></div></div><p className="muted">Your text stays in your browser and is never uploaded.</p></section><AdSlot placement="after-calculator"/><section className="contentSection"><div className="contentInner"><div className="eyebrow">WHY CHARACTER COUNTS MATTER</div><h2>Know exactly how much you wrote.</h2><p>Character limits are common in social media, titles, metadata, application forms and messaging. This tool gives you the count instantly while you type.</p><div className="guideGrid"><article><h3>With spaces</h3><p>The standard character count includes spaces, punctuation and line breaks.</p></article><article><h3>Without spaces</h3><p>Useful when a platform or assignment specifies a character limit excluding whitespace.</p></article><article><h3>Words too</h3><p>See a quick word count alongside your character totals.</p></article></div></div></section><footer><span>FameOrbit · Character Counter</span><Link href="/">Explore all FameOrbit tools</Link></footer></main>;
}
